
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-HelpRequest-placeholders","number":68,"title":"Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/68"},{"author":{"id":"U_kgDOB2-3Pg","is_bot":false,"login":"samanthwest","name":""},"headRefName":"Sam-Dining-Backend","number":67,"title":"Copy files for Backend CRUD API UCSBDiningCommonsMenuItem from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/67"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-HelpRequest-table","number":66,"title":"Table Component for HelpRequest plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/66"},{"author":{"id":"U_kgDOBXuxxw","is_bot":false,"login":"Cory-Zhao","name":"Cory Zhao"},"headRefName":"CZ-RecommendationRequest-fixtures","number":65,"title":"Create fixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/65"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-HelpRequest-form","number":64,"title":"Form Component for HelpRequest plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/64"},{"author":{"id":"U_kgDOBXuxxw","is_bot":false,"login":"Cory-Zhao","name":"Cory Zhao"},"headRefName":"CZ-RecommendationRequest-backend","number":63,"title":"Copy files for Backend CRUD API RecommendationRequest from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/63"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-HelpRequest-fixtures","number":62,"title":"Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/62"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-HelpRequest-backend","number":61,"title":"Copy files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-5pm-4/pull/61"}]
